// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Firebase import is commented out for UI-only work
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Temporarily disabled for UI development. 
/// To re-enable Firebase, uncomment the FirebaseOptions import and methods below.
class DefaultFirebaseOptions {
  /*
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8oOBn24kSmApVAirpRZqW0dpfN1zUi0',
    appId: '1:303380889177:android:e4beaaa05b6285d19e3b48',
    messagingSenderId: '303380889177',
    projectId: 'enroute-concierge',
    storageBucket: 'enroute-concierge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qJflOF-tsbwS8pvTIM9d78EnUHA_7Y0',
    appId: '1:303380889177:ios:ebde27f3f54267e09e3b48',
    messagingSenderId: '303380889177',
    projectId: 'enroute-concierge',
    storageBucket: 'enroute-concierge.firebasestorage.app',
    iosBundleId: 'com.enroute.concierge',
  );
  */
}
